# Generated by Django 6.0.1 on 2026-02-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5)),
                ('slug', models.SlugField(unique=True)),
                ('date_de_publication', models.DateTimeField()),
                ('reduction', models.FloatField()),
            ],
        ),
    ]
