# Generated by Django 6.0.1 on 2026-02-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_article_date_de_publication_alter_article_prix_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(upload_to="resources/")),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("code", "Code"),
                            ("problem", "Problem Set"),
                            ("pdf", "PDF"),
                            ("latex", "LaTeX"),
                        ],
                        max_length=10,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Article",
        ),
    ]
